generatorName: csharp
additionalProperties:
  packageName: Org.OpenAPITools
  packageGuid: "{C69F4F3D-BE68-4A19-A3F0-5EEE1810150B}"
  library: restsharp
  oseg.namespace: OSEG.PetStoreExamples
  oseg.packageGuid: "{4D6EE6C1-B6BF-402C-9D5D-C67B3A3D66B0}"
  oseg.security.api_key.api_key: YOUR_API_KEY
  oseg.security.petstore_auth.access_token: YOUR_ACCESS_TOKEN
globalProperties:
  apiTests: false
  modelTests: false
  apiDocs: false
  modelDocs: false
